version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: "increase"  # This is where you should place versioning strategy for Maven
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    labels:
      - "dependencies"
      - "java"
      - "springboot"
    open-pull-requests-limit: 2
