# Version of the application, injected from Maven
build.number=@VERSION@

# Git commit injected from Git during the build
git.commit.id=@GIT_COMMIT@

# Image tag
image.tag=@VERSION@

# Build timestamp injected from Maven during the build
build.datetime=@BUILD_TIMESTAMP@
