apiVersion: v1
kind: Service
metadata:
  name: hello-world-app
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-world-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world-app
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      containers:
      - image: nexus-repository/app-name:openshift
        name: hello-world-app
        ports:
        - containerPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: hello-world-app
spec:
  port:
    targetPort: 8080
  tls:
    termination: edge
  to:
    kind: Service
    name: hello-world-app
