# k8s/overlays/openshift/deployment-patch.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app
spec:
    template:
      spec:
        containers:
        - name: hello-world-app
          image: ""  # Image from Nexus repository
