name: CI/CD Pipeline with OPA Policy Enforcement

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - '*'

jobs:
  check-opa-policy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Clone Policy Repository
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/excellaco/policy-as-code-opa.git policies

      - name: Install OPA
        uses: actions/setup-go@v3  # Use Go action for easier OPA installation
        with:
          go-version: '^1.20' # Or your preferred Go version

      - name: Install OPA
        run: go install github.com/open-policy-agent/opa/cmd/opa@latest

      - name: Verify OPA installation
        run: opa version

      - name: Run OPA policy check
        run: |
          echo "${{ toJson(github.event) }}" > github_event.json
          opa eval --input github_event.json --data policies --entrypoint "data.policy.allow"